In [3]:
from google.colab import drive
import pandas as pd
import numpy as np

In [4]:
# Kết nối với Google Drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
# Đường dẫn đến tệp tin CSV trong Google Drive
file_path = 'https://drive.google.com/uc?id=1OQYLAEJhQN1Rg0tKTz5qZDDDEn9o3Rza' 


In [6]:
# Đọc tệp tin dữ liệu và lưu vào DataFrame
df = pd.read_csv(file_path)



In [7]:
df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0  2004-03-10  18:00:00     2.6      1360.00       150  11.881723   
1  2004-03-10  19:00:00     2.0      1292.25       112   9.397165   
2  2004-03-10  20:00:00     2.2      1402.00        88   8.997817   
3  2004-03-10  21:00:00     2.2      1375.50        80   9.228796   
4  2004-03-10  22:00:00     1.6      1272.25        51   6.518224   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0        1045.50    166.0       1056.25    113.0       1692.00      1267.50   
1         954.75    103.0       1173.75     92.0       1558.75       972.25   
2         939.25    131.0       1140.00    114.0       1554.50      1074.00   
3         948.25    172.0       1092.00    122.0       1583.75      1203.25   
4         835.50    131.0       1205.00    116.0       1490.00      1110.00   

       T         RH        AH  
0  13.60  48.875001  0.757754  
1  13.30  47.700000  0.725487  
2  11.90  53.975000  0.750239  
3  11.00  60.000000  0.786713  
4  11.15  59.575001  0.788794

*Đây là tập dữ liệu về chất lượng không khí ghi nhận tại một trạm quan trắc ở Ý. BAo gồm nhiều thuộc tính như nồng độ khí, nhiệt độ, độ ẩm,..*

In [66]:
# Kiểm tra lớp cho từng thuộc tính trong bảng
class_counts = df["PT08.S1(CO)"].value_counts()
print(class_counts)

-200.000000     366
 1099.500000     12
 954.250000      12
 986.750000      12
 888.000000      11
               ... 
 808.000000       1
 834.333333       1
 891.666667       1
 748.500000       1
 1314.250000      1
Name: PT08.S1(CO), Length: 3246, dtype: int64


In [84]:
# Kiểm tra kiểu dữ liệu 
# Nếu kết quả ra dưới dạng kiểu dữ liệu là float hoặc int là kiểu dữ liệu liên tục
print(df["NMHC(GT)"].dtypes)

int64


Chia sẻ thành tập huấn luyện và kiểm tra: 


In [8]:
from sklearn.model_selection import train_test_split

In [71]:
#Xoá các hàng có giá tị thiếu
data = df.dropna()
# Xoá các cột không cần thiết và cột nhãn 
X = data.drop(['Date',"Time"], axis=1)

# Test
y= data["Date"]
#print(y)

  - ở đây ta sử dụng hàm ***train_test_split*** từ một modun skleản.model_selection để có thể chia dữ liệu thành hai tập: 
    - Tập huấn luyện (X_train, y_train)
    - Tập kiểm tra (X_test, y_test)
  - Tham số ***stratify=y*** điều này đảm bảo rằng phân phối các lớp trong dữ liệu được giữ nguyên trong cả tập huấn luyện và tập kiểm tra.
  - Tham số ***test_size*** điều này xác định tỷ lệ dữ liệu được chia cho tệp kiểm tra( Trong trường hợp này là 30%)
  - Tham số ***random_state = 42*** là một giá trị để đảm bảo kết quả chia dữ liệu như nhau mỗi lần chạy.

In [72]:
# Chia dư liệu thành tập huấn luyện và tập kiếm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)

4. KNN classifier:


In [73]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score , recall_score, f1_score

In [74]:
# Xây dựng và đào tạo mô hình K-NN

# Khởi tạo mô hình K-NN
k=5
knn = KNeighborsClassifier(n_neighbors=k)
# Huấn luyện mô hình trên tập huấn luyện
knn.fit(X_train, y_train)

# Dự đoán nhãn cho tập kiểm tra
y_predicted = knn.predict(X_test)

#Đánh giá hiệu suất của mô hình:

# Tính toán độ chính xác
accuracy = accuracy_score(y_test, y_predicted)

# Tính toán ma trận nhầm lẫn
confustion_mtx = confusion_matrix(y_test, y_predicted)

# Tiếp tục tính toán precition, recall,và cuối cùng là f1_score
precision = precision_score(y_test, y_predicted, average=None)
recall = recall_score(y_test , y_predicted, average=None)
f1 = f1_score(y_test, y_predicted, average =None)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [75]:
print("accuracy:" , accuracy)
print("confustion_mtx", confustion_mtx)
print("precision:", precision)
print("recallrecall: ", recall)
print("f1: " , f1 )

accuracy: 0.2329059829059829
confustion_mtx [[0 1 0 ... 0 0 0]
 [0 4 2 ... 0 0 0]
 [0 1 2 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
precision: [0.         0.5        0.18181818 0.23076923 0.         0.33333333
 0.08333333 0.         0.33333333 0.3        0.33333333 0.28571429
 0.15789474 0.         0.         0.06666667 0.23076923 0.
 0.         0.66666667 0.5        0.23076923 0.07142857 0.25
 0.44444444 0.55555556 0.         0.         0.         0.
 0.75       0.         0.5        0.42857143 0.         0.14285714
 0.         0.28571429 0.16666667 0.2        0.375      0.07692308
 0.22222222 0.375      0.25       0.33333333 0.5        0.33333333
 0.2        0.66666667 0.         0.6        0.14285714 0.125
 0.         0.18181818 0.11111111 0.         0.         0.2
 0.25       0.         0.06666667 0.08333333 0.18181818 0.07142857
 0.         0.         0.11111111 0.125      0.2        0.
 0.14285714 0.125      0.14285714 0.5        1.         0.8
 0.

# Xử lý số lượng lớp trong thuộc tính quá lớn
- Gom nhóm(Clustering): Sử dụng phương pháp giom nhóm để nhóm các lớp tương đồng lại với nhau. Bằng cách này ta có thẻ giảm số lượng lớp ban đầu thành một số lượng nhóm nhỏ hơn và sau đó có thể áp dụng thuật toians K-NN trên các nhóm nhỏ hơn . Điều này có thể giúp giảm độ phức tạp và cải thiện hiệu suất của K-NN

- Giảm chiều dữ liệu ( Dimensionality reduction): Sử dụng các phương pháp giảm chiều dữ liệu như PCA (Principal Component Analysis) hoặc t-SNE( t- Distributed Stochastic Neighbor Embedding) để giảm số chiều hoặc giảm thiểu sự trùng lặp giữa các lớp, từ đó giảm số lượng lớp và cải thiện hiệu suất của K-NN

- Lựa chọn các tập con quan trọng: Thay vì làm việc toàn bộ số lượng lớp, ta có thể xem sét chỉ lựa chọn một tập con các lớp quan trọng hoặc các lớp có số lượng mẫu lớn hơn. Bằng cách này, ta có thể tập trung vào các lớp quan trọng hơn và giảmsố lương lớp cần xử lý.


**Chú ý**

***Thuật toán K-NN yêu cầu các nhãn của các mẫu là phải dưới dạng rời rạc(discrete) ***

**Nếu vẫn muốn sử thuật toán K-NN này thì phải chuyển dổi từ dạng liên tục (contiuous) thành một bài toán phân loại với các nhãn rời rạc để có thể sử dụng được thuật toán K-NN **

In [78]:
# Đoạn mã này sử dụng phương pháp gom nhóm(Clustering) 
# sử dụng vào tập dữ liệu X_train
# Ở đây đang bị lỗi vì cột dữ liệu CO(GT) này đang ở dưới dạng liên tục (Continuous)
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Xoá các hàng có giá trị thiếu
data = df.dropna()

# Xoá các cột không cần thiết và cột nhãn
X = data.drop(['CO(GT)' , "Date", "Time"], axis=1)
y = data["CO(GT)"]

# Áp dụng phương pháp gom nhóm
kmeans = KMeans(n_clusters=5)  # Giả sử chọn số nhóm là 5
cluster_labels = kmeans.fit_predict(X)

# Chia dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Thêm cột "cluster_label" vào tập huấn luyện
X_train["cluster_label"] = cluster_labels[:len(X_train)]

# Lựa chọn các mẫu từ các nhóm quan trọng
important_clusters = X_train["cluster_label"].value_counts().head(3).index
X_train_selected = X_train[X_train["cluster_label"].isin(important_clusters)]
y_train_selected = y_train[X_train["cluster_label"].isin(important_clusters)]

# Huấn luyện mô hình K-NN trên tập dữ liệu đã lựa chọn
k = 3  # Số lượng láng giềng gần nhất
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train_selected, y_train_selected)

# Đánh giá mô hình trên tập kiểm tra
accuracy = knn.score(X_test, y_test)
print("Accuracy:", accuracy)


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


ValueError: ignored

In [87]:
# Đoạn code sử dụng thuật toán hồi quy (regression) thay vì sử dụng phương pháp phân loại trong K-NN
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score , recall_score, f1_score
# Xoá các hàng có giá trị thiếu
data = df.dropna()

# Xoá các cột không cần thiết và cột nhãn
X = data.drop(['CO(GT)' , "Date", "Time"], axis=1)
y = data["CO(GT)"]

# Chia dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [88]:
# Sử dụng thuật toán hồi quy
# Khởi tạo mô hình K-NN
k = 3  # Số lượng láng giềng gần nhất trong mô hình K-NN 
# Nó sẽ lấy điểm dựa trên khoảng cách và lấy trung bình giá trị đầu ra của các điểm gần nhất đẻ dự đoán

knn = KNeighborsRegressor(n_neighbors=k)

# Huấn luyện mô hình trên tập huấn luyện
knn.fit(X_train, y_train)

# Dự đoán trên tập kiểm tra
y_pred = knn.predict(X_test)

# Đánh giá mô hình
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)




Mean Squared Error: 2625.509194365305
R-squared: 0.5491998491506324


In [89]:
#----
# Chuyển đổi thành bài toán phân loại với ngưỡng
threshold = 1.5
y_pred_class = [1 if val >= threshold else 0 for val in y_pred]
y_test_class = [1 if val >= threshold else 0 for val in y_test]

# Đánh giá hiệu suất
accuracy = accuracy_score(y_test_class, y_pred_class)
confusion = confusion_matrix(y_test_class, y_pred_class)
precision = precision_score(y_test_class, y_pred_class)
recall = recall_score(y_test_class, y_pred_class)
f1 = f1_score(y_test_class, y_pred_class)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.88497150997151
Confusion Matrix:
 [[1242  109]
 [ 214 1243]]
Precision: 0.9193786982248521
Recall: 0.8531228551818806
F1 Score: 0.8850124599501603
